package com.example.core

import android.content.Context
import android.util.Log
import com.example.BuildConfig
import com.example.data.ai.DirectGeminiPhotoVerificationService
import com.example.data.ai.DirectGeminiSpeciesIdentificationService
import com.example.data.ai.GeminiPhotoVerificationService
import com.example.data.ai.GeminiSpeciesIdentificationService
import com.example.data.ai.MockPhotoVerificationService
import com.example.data.ai.MockSpeciesIdentificationService
import com.example.data.auth.LocalAuthRepository
import com.example.data.auth.SessionStore
import com.example.data.local.BiomateDatabase
import com.example.data.location.FusedLocationProvider
import com.example.data.location.LocationProvider
import com.example.data.repository.local.LocalBadgeRepository
import com.example.data.repository.local.LocalChallengeRepository
import com.example.data.repository.local.LocalConnectionRepository
import com.example.data.repository.local.LocalMessagingRepository
import com.example.data.repository.local.LocalProfileRepository
import com.example.data.repository.local.LocalRewardRepository
import com.example.data.repository.local.LocalSessionRepository
import com.example.data.repository.local.LocalTrailMomentRepository
import com.example.data.repository.local.LocalTrailRepository
import com.example.data.repository.local.LocalTripRepository
import com.example.data.repository.local.PhotoStore
import com.example.data.seed.DevSeeder
import com.example.data.storage.LocalPhotoStore
import com.example.data.weather.OpenMeteoWeatherService
import com.example.domain.ai.PhotoVerificationService
import com.example.domain.ai.SpeciesIdentificationService
import com.example.domain.repository.AuthRepository
import com.example.domain.repository.BadgeRepository
import com.example.domain.repository.ChallengeRepository
import com.example.domain.repository.ConnectionRepository
import com.example.domain.repository.MessagingRepository
import com.example.domain.repository.ProfileRepository
import com.example.domain.repository.RewardRepository
import com.example.domain.repository.SessionRepository
import com.example.domain.repository.TrailMomentRepository
import com.example.domain.repository.TrailRepository
import com.example.domain.repository.TripRepository
import com.example.domain.repository.WeatherService
import com.google.firebase.FirebaseApp
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope

/** Manual dependency graph for Biomate. */
class AppContainer(
    private val context: Context,
    private val appScope: CoroutineScope
) {

    /** True when a Firebase project is configured for this build. */
    val isFirebaseConfigured: Boolean by lazy {
        val available = runCatching { FirebaseApp.initializeApp(context) != null }.getOrDefault(false)
        Log.i(
            TAG,
            if (available) {
                "Firebase configured — using cloud-capable services."
            } else {
                "No google-services.json found — using the local backend. Data stays on this device."
            }
        )
        available
    }

    /**
     * GEMINI_API_KEY is generated by the Secrets Gradle Plugin from `.env` / local.properties.
     * Placeholder values from `.env.example` are treated as not configured.
     */
    private val geminiApiKey: String? by lazy {
        BuildConfig.GEMINI_API_KEY
            .trim()
            .takeUnless {
                it.isBlank() ||
                    it == "MY_GEMINI_API_KEY" ||
                    it == "YOUR_GEMINI_API_KEY"
            }
    }

    private val database: BiomateDatabase by lazy {
        BiomateDatabase.getDatabase(context.applicationContext, appScope)
    }

    private val dao by lazy { database.daoV2() }
    private val sessionStore by lazy { SessionStore(context.applicationContext) }

    val photoStore: PhotoStore by lazy { LocalPhotoStore(context.applicationContext) }
    val locationProvider: LocationProvider by lazy { FusedLocationProvider(context.applicationContext) }
    val weatherService: WeatherService by lazy { OpenMeteoWeatherService() }

    /**
     * Camera challenge verification priority:
     * 1) a local GEMINI_API_KEY for the hackathon build;
     * 2) Firebase AI Logic when Firebase is configured;
     * 3) deterministic offline fallback.
     */
    val photoVerification: PhotoVerificationService by lazy {
        val mock = MockPhotoVerificationService()
        when {
            geminiApiKey != null -> {
                Log.i(TAG, "Gemini API key configured — enabling live AI photo verification.")
                DirectGeminiPhotoVerificationService(
                    apiKey = geminiApiKey!!,
                    fallback = mock
                )
            }
            isFirebaseConfigured -> GeminiPhotoVerificationService(fallback = mock)
            else -> mock
        }
    }

    /** Same priority order for Explore-mode outdoor identification. */
    val speciesIdentification: SpeciesIdentificationService by lazy {
        val mock = MockSpeciesIdentificationService()
        when {
            geminiApiKey != null -> {
                Log.i(TAG, "Gemini API key configured — enabling live AI outdoor identification.")
                DirectGeminiSpeciesIdentificationService(
                    apiKey = geminiApiKey!!
                )
            }
            isFirebaseConfigured -> GeminiSpeciesIdentificationService(fallback = mock)
            else -> mock
        }
    }

    private val seedingComplete = CompletableDeferred<Unit>()

    suspend fun awaitSeeded() = seedingComplete.await()

    val authRepository: AuthRepository by lazy {
        LocalAuthRepository(dao, sessionStore, awaitReady = ::awaitSeeded)
    }

    val profileRepository: ProfileRepository by lazy { LocalProfileRepository(dao) }
    val trailRepository: TrailRepository by lazy { LocalTrailRepository(dao) }
    val connectionRepository: ConnectionRepository by lazy { LocalConnectionRepository(dao) }
    val tripRepository: TripRepository by lazy { LocalTripRepository(dao) }
    val messagingRepository: MessagingRepository by lazy { LocalMessagingRepository(dao) }
    val trailMomentRepository: TrailMomentRepository by lazy { LocalTrailMomentRepository(dao) }
    val rewardRepository: RewardRepository by lazy { LocalRewardRepository(dao) }
    val badgeRepository: BadgeRepository by lazy { LocalBadgeRepository(dao) }
    val sessionRepository: SessionRepository by lazy { LocalSessionRepository(dao) }

    val challengeRepository: ChallengeRepository by lazy {
        LocalChallengeRepository(
            dao = dao,
            rewards = rewardRepository,
            photoVerification = photoVerification,
            photoStore = photoStore
        )
    }

    suspend fun seedIfNeeded() {
        try {
            trailRepository.ensureSeeded()
            if (!isFirebaseConfigured) {
                DevSeeder(dao).seed()
            }
        } catch (e: Exception) {
            Log.e(TAG, "Seeding failed; continuing without demo content", e)
        } finally {
            seedingComplete.complete(Unit)
        }
    }

    private companion object {
        const val TAG = "AppContainer"
    }
}
